version: '3.9'

services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dgdband@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5051:80'
