version: '3.9'

services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dgdband@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5051:80'
    depends_on:
      - postgres

  mysql:
    image: mysql:5.7.38-oracle
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:apache
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
